docs: translate contribution guidelines en->zh
traas-stack/kapacity-website pull request #7
Opened 2023-06-10 10:39 UTC by niconical

fix #6

2023-06-10 10:40 UTC, niconical commented
/assign @zqzten

2023-06-11 05:18 UTC, zqzten requested changes

2023-06-11 05:18 UTC, zqzten commented on content/zh-cn/docs/contribution-guidelines/_index.md
> +这是一些贡献的指南。
```suggestion
以下是一些具体的贡献指南。
```

2023-06-11 05:18 UTC, zqzten commented on content/zh-cn/docs/contribution-guidelines/_index.md
> +## 提交问题
```suggestion
## 提交 Issue
```

2023-06-11 05:18 UTC, zqzten commented on content/zh-cn/docs/contribution-guidelines/_index.md
> +在提交问题之前，请检查是否已经存在类似的问题，避免重复。
```suggestion
在提交 Issue 之前，请检查是否已经存在类似的 Issue，避免重复。
```

2023-06-11 05:18 UTC, zqzten commented on content/zh-cn/docs/contribution-guidelines/_index.md
> +如果要报告安全漏洞，请务必在 `New issue` 中选择 `Report a security vulnerability` 选项。 不要将其作为普通的公共问题提交。
```suggestion
如果要报告安全漏洞，请务必在 `New issue` 中选择 `Report a security vulnerability` 选项。不要将其作为普通的公开 Issue 提交。
```

2023-06-11 05:25 UTC, niconical commented
Thanks, I've modified the corresponding translations based on your suggestions.

2023-06-11 05:40 UTC, zqzten approved these changes
LGTM, thanks! ❤️

2023-06-11 05:42 UTC, merged